markdown: kramdown
permalink: /:title
url: "http://nodeschool.io/montreal"
timezone: America/Montreal

kramdown:
  input: GFM

# Use the following plug-ins
gems:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: :compressed

# Exclude these files from your production _site
exclude:
  - README.md
  - .editorconfig
  - Procfile
  - .sass-cache/
  - tasks/

mentors:
  - name: pcuci
    twitter: pcuci
  - name: david
    twitter: davidrowley514
  - name: cassie
    twitter: cassierheaume
  - name: valeri
    twitter: vicneanschi
