markdown: kramdown
permalink: /:title
url: "http://nodeschool.io/montreal"
timezone: America/Montreal

kramdown:
  input: GFM

# Use the following plug-ins
plugins:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: :compressed

# Exclude these files from your production _site
exclude:
  - README.md
  - .editorconfig
  - Procfile
  - .sass-cache/
  - tasks/

mentors:
  - name: pcuci
    twitter: pcuci
  - name: cassie
    twitter: cassierheaume
  - name: matan
    twitter: matchai
  - name: valeri
    twitter: vicneanschi
  - name: ruyadorno
    twitter: ruyadorno
  - name: david
    twitter: davidrowley514
  - name: ziad-saab
  - name: harris
    twitter: LulzHRK
  - name: nicolas
    twitter: nicolasgere
  - name: rsayar
    twitter: ramisayar
  - name: andre-john
    twitter: ajmas
  - name: ehren
    twitter: EhrenLillies
  - name: marekweb
    twitter: marekweb
  - name: fcharette
    twitter: fed135
  - name: shawn
    twitter: plansmash
  - name: mats
    twitter: boozangcloud
  - name: kareniel
    twitter: Jonathan_Dupre
  - name: richardlitt
    twitter: richlitt
  - name: xavier
    twitter: XDrdak
  - name: razvan
    twitter: RazvanLM
